name: generate-art
on:
  repository_dispatch:
    types: [generate]   # Pi fires this

jobs:
  infer:
    runs-on: [self-hosted, gpu]    # tag your runner
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with: { python-version: "3.10" }

    - name: Install deps
      run: pip install diffusers[torch]==0.28.0 accelerate pillow

    - name: Run inference
      run: |
        python scripts/infer.py \
          --input-path input/${{ github.event.client_payload.photo }} \
          --output-dir output/

    - name: Push art back
      run: |
        git config user.name "ArtBot"
        git config user.email "actions@github.com"
        git add output/
        git commit -m "new art $(date +%s)"
        git push
